### ISSUE TITLE
Bug alert! Gradient-restoration rate plotter

### ISSUE THREAD

**Issue by munizlgmn** [araujolma/SOAR#40]
I had some problems with the plot "Gradient-restoration rate history" for the Cart problem. I received a value error because data has no positive values and therefore cannot be log-scaled. Please check this error. @araujolma

**Comment by araujolma** [comment]
I think this is solved (in the stupidest possible way, of course). I am going to upload it shortly.

However, I must say, since I was not perceiving this as a bug, I think your python/spyder is out of date. My versions:

python: 3.6.1
spyder: 3.2.4

**Comment by araujolma** [comment]
Closing this now.
