### ISSUE TITLE
Create new folders to organize simulation results 

### ISSUE THREAD

**Issue by munizlgmn** [araujolma/SOAR#47]
A good idea to organize the output files of a given simulation is to generate a new folder that contains all the information related to that simulation. Main requirements of this new functionality:

1) A folder needs to have a specific ID. For example: "Simulation Nº XX" or "Simulation Date and Time" ;

2) Each new simulation generates it's own new folder;

3) All plot files of a given simulation must be inside it's own folder;

4) A file containing all the simulation parameters (vehicle parameters, boundary values, environment constants and solver parameters for ITS ME and SOAR) must be generated by the program to summarize in one place the setup of the simulation.

**Comment by araujolma** [comment]
Done!
