### ISSUE TITLE
Memory error with prob101

### ISSUE THREAD

**Issue by munizlgmn** [araujolma/SOAR#65]
In prob101: after 150 grad iterations, function restRnds present an error called "Memory Error".

**Comment by araujolma** [comment]
I left my computer running prob101, and it passed well through 1000 grad iterations without any problem. Weird...

**Comment by munizlgmn** [comment]
Maybe the problem is related to the sequential mode (non parallel mode) of the SOAR.  Still having problems with prob9_1 and prob9_2.

**Comment by araujolma** [comment]
I ran prob9_1 and no error. Let's debug this properly, shall we?

Which "case" are you running, exactly? When does this memory error show up? Always at the same "time"?

**Comment by munizlgmn** [comment]
I think the problem is solved. I updated Python package dill (pickle....) and the memory error is no longer occurring.
